version: '1.0'
services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'cityWeather'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d

  api:
    build: ./cityWeather_api
    restart: always

  scraper:
    build: ./cityWeather
    restart: always
    environment:
      DB.HOST: 'db'
      DB.USER: 'user'
      DB.PASSWORD: '123456'
      DB.NAME: 'cityWeather'