version: '1.0'
services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'cityWeather'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    expose:
      - '3306'

  scraper:
    build: ./cityWeather
    restart: always
    environment:
      DB_HOST: 'db'
      MYSQL_DATABASE: 'cityWeather'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
      
  api:
    build: ./cityWeather_api
    restart: always
    environment:
      DB_HOST: 'db'
      MYSQL_DATABASE: 'cityWeather'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
    ports:
      - '127.0.0.1:8000:8000'
    expose:
      - '8000'